deploy tensorflow on ecs instance
alibabacloud-automation/terraform-alicloud-market-tensorflow pull request #1
Opened 2020-02-14 08:32 UTC by lixue323

2020-02-14 09:27 UTC, zql-tqy commented on examples/complete/README.md
> +# Complete Market Wordpress  example
这个没改吧

2020-02-14 09:27 UTC, zql-tqy commented on examples/complete/main.tf
> +  image_id                   = "m-2zef6ik849mkvyn63xpc"
镜像的还是加几个****吧

2020-02-14 09:27 UTC, zql-tqy commented on CHANGELOG.md
> +IMPROVEMENTS：
第一个版本不用加improvement吧

2020-02-14 11:29 UTC, xiaozhu36 requested changes

2020-02-14 11:29 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  ingress_rules       = ["all-all"]
如果是要登陆但ecs上去用的化，我理解只开放22 和80 端口就行

2020-02-14 11:29 UTC, xiaozhu36 commented on outputs.tf
> +output "this_ecs_instance_public_ip" {
outputs中要把一些最基本的实例信息输出出来

2020-02-14 11:29 UTC, xiaozhu36 commented on main.tf
> +  image_id                    = var.image_id
这个地方忘记了，要加一个create的开关，设置默认值为true

2020-02-14 11:29 UTC, xiaozhu36 commented on variables.tf
> +  description = "The virtual switch ID to launch ECS and RDS MySql instance in VPC."
这里面没有rds啥事吧

2020-02-14 11:29 UTC, xiaozhu36 commented on variables.tf
> +  description = "The image id used to launch one ecs instance. It only support CentOS_7."
这个必须是centos么

2020-02-17 09:49 UTC, xiaozhu36 requested changes

2020-02-17 09:49 UTC, xiaozhu36 commented on outputs.tf
> +  value = concat(alicloud_instance.this.*.internet_charge_type, [""])[0]
缺少description

2020-02-17 09:49 UTC, xiaozhu36 commented on variables.tf
> +variable "product_name_prefix" {
product_keyword

2020-02-17 09:49 UTC, xiaozhu36 commented on variables.tf
> +  description = "The image id used to launch one ecs instance. If it is '', Alibaba Cloud market place image will be used"
The image id used to launch one ecs instance. If not set, a fetched market place image by product_keyword will be used.

2020-02-17 09:49 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
给你一个default：cloud_ssd

2020-02-17 09:49 UTC, xiaozhu36 commented on variables.tf
> +  description = "A mapping of tags to assign to the ECS and SLB."
这里面没有slb吧

2020-02-17 09:49 UTC, xiaozhu36 commented on main.tf
> +  configuration_source    = "terraform-alicloud-modules/terraform-alicloud-market-tensorflow"
configuration_source    = "terraform-alicloud-modules/market-tensorflow"

2020-02-17 09:49 UTC, xiaozhu36 commented on main.tf
> +
按照https://github.com/terraform-alicloud-modules/terraform-alicloud-ecs-instance/blob/master/main.tf#L20 也加一个description吧："An ECS instance used to deploy Tensorflow."

2020-02-20 13:02 UTC, xiaozhu36 requested changes

2020-02-20 13:02 UTC, xiaozhu36 commented on variables.tf
> +variable "data_disks" {
这个参数没见你在main中使用啊
其他的参数也要检查下，不用的参数要去掉，有用的参数要加上

2020-02-20 14:55 UTC, xiaozhu36 approved these changes

2020-02-20 14:55 UTC, merged